#!/usr/bin/env bash

[ -n "${TGENV_DEBUG}" ] && set -x

echo "Usage: tgenv <command> [<options>]

Commands:
   install           Install a specific version of Terragrunt
   use               Switch a version to use
   uninstall         Uninstall a specific version of Terragrunt
   list              List all installed versions
   list-remote       List 20 most recent installable versions
   list-remote-all   List all installable versions
"
