#!/usr/bin/env bash
#set -e

[ -n "${TGENV_DEBUG}" ] && set -x
source ${TGENV_ROOT}/libexec/helpers

if [ ${#} -ne 0 ];then
  echo "usage: tgenv list-remote" 1>&2
  exit 1
fi

curlw -sf https://api.github.com/repos/gruntwork-io/terragrunt/git/refs/tags | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta|alpha)[0-9]+)?" | uniq | sort -t . -k 1nr,1 -k 2nr,2 -k 3nr,3
